#!/bin/bash


clear
echo ""
echo -e "\e[0;90m"
# -- config files --
source conf/github-repos
source conf/setup-ini
# -- code files --
source .syslib/data
source .syslib/utils
source .syslib/syscore
echo -e "\e[0m"


on_exit () {
   echo_call "on_exit"
   echo_dbg " -- run-1st-as-root end -- "
   echo ""
}


trap on_exit EXIT


if (( $UID != 0 )); then
   echo ""
   echo_neg "-- [ YOU MUST RUN THIS SCRIPT AS ROOT ] --"
   echo ""
   exit 1
fi


echo ""
echo -e "\e[0;90m"
# -- install python venv: just in case if not instaled
apt install python3-venv
echo -e "\e[0m"
err_code=$?
if (( err_code != 0 )); then
   echo_neg "error-installing"
   exit 1
fi


echo "PYTHON3-VENV-OK" > .logs/py3venv-run
echo_pos "Run 'setup' script now as your normal 'login user' (logout as root)"
exit 0
