#!/bin/bash


echo -e "${BLDGRN} + lib-file: .syslib/syscore${ECLR}"



is_py3_11_installed () {

   echo "" && echo -e " ${BLDBLU}(( is_py3_11_installed ))${ECLR}"


   return 0
}


install_py3_11 () {

   echo "" && echo -e " ${BLDBLU}(( install_py3_11 ))${ECLR}"
   echo "   cwd: $(pwd)"

   return 0

}

# ---
#
#
create_py_venv () {

   echo "" && echo -e " ${BLDBLU}(( create_py_venv ))${ECLR}"
   echo "   cwd: $(pwd)"

   PY_3_11_INSTALLED=$(is_py3_11_installed)
   if [[ $PY_3_11_INSTALLED  == 0 ]]; then
      install_py3_11
   fi


   pydir311="pyvenvs/py3.11"
   if [ -d "$pydir311" ]; then
      echo "" && echo -e "  ${GRN}<< FOLDER__FOUND: $pydir311 >>${ECLR}"
      echo -e "    ${GRN}PYTHONv3.11 venv seems to installed!${ECLR}"
      sleep 4
   else
      echo "" && echo -e "  ${RED}[ FOLDER_NOT_FOUND: $pydir311 ]${ECLR}"
      sleep 2
      mkdir "$pydir311"  -p
   fi

#   if ! [ -x "$(python3.11 -v foo)" ]; then
#      echo "python3.11 not installed"
#      exit 2
#   fi

   test -x "$(which python3.11x)"

   echo "" && echo "[ INSTALLING PYTHON v3.11 ]" && echo ""
   CMD_TO_FIND="python3.11"
   HERE_IS_PY311=$(whereis "$CMD_TO_FIND")
   echo -e "  ${BLDGRN}HERE_IS_PY311 / $HERE_IS_PY311${ECLR}"

   blnk=""
    # shellcheck disable=SC2001
   buff=$(echo "$HERE_IS_PY311" | sed "s/$CMD_TO_FIND/$blnk/")
   echo "buff: $buff"

   #   if []
   add-apt-repository ppa:deadsnakes/ppa
   apt update
   apt install python3.11

   return 0

}


clone_repo () {

   echo "" && echo -e " ${BLDBLU}(( clone_repo ))${ECLR}"
   echo "   token: $1"
   echo "   url: $2"
   echo "   cwd: $(pwd)"

   # shellcheck disable=SC2001
   repo_url=$(echo "$2" | sed "s/TOKEN/$1/")
   echo -e "   ${BLU}$repo_url${ECLR}"

   echo -e "${GRY}"
   git clone "$repo_url"
   echo -e "${ECLR}"

   return 0

}