#!/bin/bash


echo "loading: .syslib/utils"


gry_block () {
   echo -e "\e[0;90m"
}


gry_block_end () {
   echo -e "\e[0m"
}


echo_bylw () {
   echo -e "${BLDYLW}$1$ECLR"
}


echo_color () {
   echo -e "$1$2$ECLR"
}


echo_pos () {
   echo -e "${GRN}  + $1 $ECLR"
}


echo_neg () {
   echo -e "${RED}  - $1 $ECLR"
}


echo_warning () {
   echo -e "${YLW}  - $1 $ECLR"
}


echo_dbg () {
   echo -e "${DBG}    > $1 $ECLR"
}


echo_call () {
   echo "" && echo -e "$BLU(( ${FUNCNAME[1]} )) $ECLR"
}


echo_call_end () {
   echo -e "${GRY} -- callend/ ${FUNCNAME[1]} --$ECLR"
   echo ""
}


echo_info () {
   echo -e "${BLDBLU}INFO: " && echo -e "${BLU}  * $1 ${ECLR}"
   echo ""
}


echo_pnf () {
   echo_neg "PATH_NOT_FOUND: $1"
}


echo_pok () {
   echo_pos "PATH_FOUND: $1"
}


echo "load: OK"
