#!/bin/bash


echo "loading: conf/github-repos"

declare -a GH_REPOS
declare -a GH_CUSTOM_REPOS

# -- do not change any of these; please :) --
GH_REPOS+=("https://TOKEN@github.com/iotech-systems/ue-core.git") 
GH_REPOS+=("https://TOKEN@github.com/iotech-systems/ue-pyengine.git")
GH_REPOS+=("https://TOKEN@github.com/iotech-systems/ue-simui.git")
GH_REPOS+=("https://TOKEN@github.com/iotech-systems/ue-simbridge.git")
GH_REPOS+=("https://TOKEN@github.com/iotech-systems/ue-simcli.git")

echo "load: OK"
