#!/bin/bash


echo "loading: conf/setup-ini"

CONF_DEFAULT_INSTALL_PATH="/opt/iotech/simeng"
CONF_INSTALL_PATH=""
# CONF_PY_VENVS_ROOT="py-venvs"
# CONF_PY_VENV_FOLDER="py3.13"
# CONF_PY_VENV_VER="python3.13"

echo "load: OK"
