#!/bin/bash


echo -e "\e[0;90m"
source .syslib/include
echo -e "\e[0m"


on_exit () {
   echo_call "on_exit"
   echo_dbg " -- run-1st-as-root/ end -- "
   echo "" && echo "" && echo ""
}


if (( $UID != 0 )); then
   echo ""
   echo_dbg "[ This script MUST run under ROOT ! ]"
   echo "" && echo ""
   sleep 4
   exit 0
fi


trap on_exit EXIT

# -- -- apt installs -- --
echo_dbg "installing: figlet"
apt install figlet -y &> /dev/null
err0=$?
echo_dbg "installing: toilet"
apt install toilet -y &> /dev/null
err1=$?
echo_dbg "installing: python3-venv"
apt install python3-venv -y &> /dev/null
err2=$?
echo_dbg "running apt: autoremove"
apt autoremove -y &> /dev/null
errX=$?

echo_dbg "[ error-codes: $err0 | $err1 | $err2 | $errX ]"

iotech_hdr

set_install_path
path_err=$?

run_preinstall
