#!/bin/bash

. .syslib/data
. .syslib/syscore

echo ""


if [ ! -f "$TOKEN_FILE" ]; then
   echo -e "  ${BLDRED}TOKEN_FILE_NOT_FOUND: $TOKEN_FILE${ECLR}"
   echo -e "    ${RED}Please request git-token from iotech.systems in order to complete this setup.${ECLR}"
   echo ""
   exit 1
fi


GTOKEN=$(cat "token-file")
echo " -> GTOKEN: $GTOKEN"




echo ""
echo " -- setup end -- "
echo ""
