#!/bin/bash


clear
echo ""


echo -e "\e[0;90m"
# -- config files --
source conf/github-repos
source conf/setup-ini
# -- code files --
source .syslib/data
source .syslib/utils
source .syslib/syscore
echo -e "\e[0m"


on_exit () {
   echo_call "on_exit"
   echo_dbg " -- setup end -- "
   echo ""
}


trap on_exit EXIT


check_custom_dependencies
deps_check_err=$?
if (( $deps_check_err != 0 )); then
   echo_neg "ERROR_CHECKING_CUSTOM_DEPENDENCIES"
   exit 1
else
   echo_pos "CHECKING_CUSTOM_DEPENDENCIES_OK"
fi

START_FLD=$(pwd)
cd "$GHROOT" || exit 1
echo_pos "[ SYSTEM INSTALL FOLDER: $GHROOT ]"


# -- create py venv --
create_py_venv "$PY_VENV_VER_SETUP" "$PY_VENV_FOLDER"
py_venv_err=$?
if (( py_venv_err != 0 )); then
   echo_neg "UNABLE_TO_INSTALL_PY_VENV: $PY_VENV_VER_SETUP in $PY_VENV_FOLDER"
   exit 1
else
   echo_pos "PY_VENV_INSTALLED: $PY_VENV_VER_SETUP in $PY_VENVS_ROOT/$PY_VENV_FOLDER"
fi


pip_install_py_venv
pip_err_code=$?


echo_dbg "[ CLONING_GITHUB_REPOS ]"
echo_pos "[ GTOKEN: $GTOKEN ]"
cd "$GHROOT" || exit 1
echo_dbg "$(pwd)"

echo ""
echo_bylw "= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = ="
clone_def_repos "$GTOKEN"

echo_bylw "= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = ="
clone_cust_repos "$GTOKEN"

echo ""
echo_pos "[ CLONING_GITHUB_REPOS_DONE ]"
echo ""
echo_bylw "= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =" 
echo ""


echo_info "Installing SIMCLI"


PYTHON_PATH="$GHROOT/ue-core"
echo_dbg "[ PYTHON_PATH: $PYTHON_PATH ]"
if [[ ! -d "$PYTHON_PATH" ]]; then
   echo_neg "PYTHON_PATH_NOT_FOUND: $PYTHON_PATH"
else
   export PYTHONPATH="$PYTHON_PATH"
fi

SIM_CLI="$PYTHON_PATH/cli/simcli"
BIN_FLD="$GHROOT/$PY_VENVS_ROOT/$PY_VENV_FOLDER/bin"

echo_dbg "[ BIN_FLD: $BIN_FLD ]"
ln -s "$SIM_CLI" "$BIN_FLD/simcli" -f
echo ""
# ls -ls "$BIN_FLD"
# echo ""

# write PATH to cli folder into the venv setup
# url: https://www.aocks.com/posts/managing-paths-in-python-virtual-environments/
pth_fld="$GHROOT/$PY_VENVS_ROOT/$PY_VENV_FOLDER/lib/python3.13/site-packages"
[[ ! -d "$pth_fld" ]] && echo_neg "PATH_NOT_FOUND: $pth_fld"

# "/eu-core-cli.pth"
pth_file_path=$pth_fld/eu-core-cli.pth
# echo_dbg "pth-file-path: $pth_file_path"
# echo "$PYTHON_PATH/cli" > $pth_file_path

# deactivate
# echo_dbg "SYS-PATH: $PATH"
# check_venv_py_ver "$GHROOT/$PY_VENVS_ROOT/$PY_VENV_FOLDER"
# echo_dbg "VENV-PATH: $PATH"

echo ""
sleep 1
echo_pos "[[ TESTING_SIMCLI: if you see text | iotech.systems - simcli | below -> simcli is installed in VENV ! ]]"
echo -e "$YLW"
simcli --help
echo -e "$ECLR"
echo ""
