#!/bin/bash

source .syslib/data
source .syslib/utils
source .syslib/syscore


on_exit () {
   echo ""
   echo " -- sync end -- "
   echo ""
}


trap on_exit EXIT


echo ""
if [ ! -f "$TOKEN_FILE" ]; then
   echo -e "  ${BLDRED}TOKEN_FILE_NOT_FOUND: $TOKEN_FILE${ECLR}"
   echo -e "    ${RED}Please request git-token from iotech.systems in order to complete this setup.${ECLR}"
   echo ""
   exit 1
fi


GTOKEN=$(cat "token-file")
echo " -> GTOKEN: $GTOKEN"

# -- move to github folder --
GHROOT=$(cat "github-root")
if [ ! -d "$GHROOT" ]; then
   echo -e "  ${BLDRED}FOLDER_NOT_FOUND: $GHROOT${ECLR}" && echo ""
   exit 2
fi

cd "$GHROOT" || exit 1


for d in $(ls); do
   if [[ "$d" = ue-*  ]]; then
      echo "" && echo "ue: $d"
      cd "$d"
      git pull -f
      cd ..
      sleep 1
   fi
done

